require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
use_frameworks!

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}

  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
      def pod.build_type;
        # Uncomment the line corresponding to your CocoaPods version
        Pod::BuildType.static_library # >= 1.9
        # Pod::Target::BuildType.static_library # < 1.9
      end
    end
  end
end

target 'GrpcClientExample' do
  #  use_modular_headers!
  config = use_native_modules!
  
  use_react_native!(:path => config["reactNativePath"])
  
  pod 'react-native-grpc-client', :path => '../..'
  
  #    pod 'SwiftGRPC'
#  pod 'gRPC-Swift', '~> 1.5.0', :modular_headers => true # Latest at the time of writing
#  pod 'gRPC-Swift-Plugins'
  #  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  #  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec', :modular_headers => true
  
  permissions_path = '../node_modules/react-native-permissions/ios'

    pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
    pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
    pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
    pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
    pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
    pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
    pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
    pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
    pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
    pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
    pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
    pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
    pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
    pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
    pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
    pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"
    pod 'Permission-Siri', :path => "#{permissions_path}/Siri"
    pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"
    pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit"
    
#    use_flipper!({ 'Flipper' => '0.95.0' })
#    post_install do |installer|
#      flipper_post_install(installer)
#    end
end
